language: java

jdk:
  - oraclejdk8

services: docker

branches:
  except: /^[0-9]/

env:
  global:
    - TZ='Europe/Oslo'
    - RELEASE_VERSION="$(git fetch --unshallow || true && git rev-list --count $TRAVIS_COMMIT)"
    - DOCKER_IMAGE_FULL_NAME="navikt/henvendelsesarkiv:$RELEASE_VERSION"
    - APPLICATION_NAME='henvendelsesarkiv'

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew clean test fatJar
  - docker build --build-arg app_name="$APPLICATION_NAME" -t "$DOCKER_IMAGE_FULL_NAME" .

deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push "$DOCKER_IMAGE_FULL_NAME"
  on:
    branch: master

after_deploy:
  - git remote add auth-origin "https://${GITHUB_ACCESS_TOKEN}@github.com/${TRAVIS_REPO_SLUG}"
  - git tag $RELEASE_VERSION
  - git push auth-origin --tags

notifications:
  slack:
    secure: e28E3AlRM28ByukSj8KX1A+alKIxGVfsLsoQgLywC5H9UbGCSlXar4AE1Io1HlogytNW+o6vp2IYHlDPq3sgjDtEhThH5qQd5l3LXiJsmmG3HSw4YIdLv+OxWANBJdruDc19iReo53bB9bLbwpi+XFHVy6TAFuxtUX/f7dU3wVSPgp3K5ZhWglLjk1hH1apJJ1Gg2lgyiYnsK65zFgYDT1la053AWqh0hdc+AdyldGHXhlIX037Qj618Ci/m8dx3O77V5U+GAyAKY0QynVme3BG7Uw1r9lxPWdKp5A/U02n6s3RdPEw5IUJ+EbEDBjmd9NMT4A7Q3yBhZpQPUYB084wX8wwdeMDVvnGwImCZ7NYfg+iDR6D6+LqpD4z2yag8txcdoGuzxVot+JhhYJ9lcu7wsEX+KgF0+BGgIQsKoneZUyw0gVYFcAkDqU7oQg0DLE0VDMCIjbfwM0/juxoutRiwmslWRV/0MFDWSSWnQBEsBHKOhAEtqcYTaZ2tfk4rCFpVRWt1Q+APfEtySmTGd4CTOxvK399SA3Ovjb2MV96yRu3Y7jMg5mh31NxqeOjLrU9vu/8aBUo9EKgPuTsnr6m6AmIopnSrtXrBkMZja/+9L1cePFPa/6KSwOsJ4v+7oiBa+evDJmxWj3M3JLbH18xbf5iZFVRx8BpUVT+A+x8=
