---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: henvendelsesarkiv2
  namespace: default
  labels:
    team: personoversikt
spec:
  image: "{{image}}"
  port: 8080
  ingresses:
  - https://henvendelsesarkiv2.nais.adeo.no
  liveness:
    path: isAlive
    initialDelay: 60
  readiness:
    path: isReady
    initialDelay: 60
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    requests:
      cpu: 250m
      memory: 1536Mi
    limits:
      cpu: 500m
      memory: 2366Mi
  vault:
    enabled: true
    paths:
    - kvPath: /oracle/data/prod/creds/henvendelsearkiv-user
      mountPath: /var/run/secrets/nais.io/db_user
    - kvPath: /oracle/data/prod/config/henvendelsearkiv
      mountPath: /var/run/secrets/nais.io/db_config
    - kvPath: /serviceuser/data/prod/srvhenvendelsesarkiv2
      mountPath: /var/run/secrets/nais.io/service_user
    - kvPath: /apikey/appdynamics/prod
      mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: APP_NAME
      value: "henvendelsesarkiv2"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: APP_ENVIRONMENT
      value: "p"
    - name: ABAC_PDP_ENDPOINT_URL
      value: "https://wasapp.adeo.no/asm-pdp/authorize"
    - name: SECURITY_TOKEN_SERVICE_JWKS_URL
      value: "https://security-token-service.nais.adeo.no/rest/v1/sts/jwks"
    - name: SECURITY_TOKEN_SERVICE_ISSUER_URL
      value: "https://security-token-service.nais.adeo.no"
